suppressMessages({
    library(data.table)
    library(magrittr)
    library(lubridate)
    library(purrr)
    library(plyr)
    library(glue)
    library(phenofit)
    library(stringr)
    library(Ipaper) # devtools::install_github("kongdd/Ipaper")
    library(sp2)    # devtools::install_github("kongdd/sp2")
    library(ncdf4)
    library(sp)
    library(raster)
    library(foreach)
    library(iterators)
})
# source("../../R/fix_phenofit.R")
